// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Test.Model
{
    public partial class Employee
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }

        [StringLength(50)]
        public string Name { get; set; }

        [Column(TypeName = "date")]
        public DateTime? DateOfBirth { get; set; }

        [Required]
        [StringLength(50)]
        public string Phone { get; set; }

        [Column("Department_id")]
        public int? DepartmentId { get; set; }

        [Column("IMG_URL")]
        public string ImgUrl { get; set; }

        [StringLength(50)]
        [EmailAddress]
        public string Email { get; set; }

        public bool? Gender { get; set; }

        [ForeignKey(nameof(DepartmentId))]
        [InverseProperty("Employee")]
        public virtual Department Department { get; set; }
    }
}